### ISSUE TITLE
looks like it's heavily influenced from gorails

### ISSUE THREAD

**Issue by localhostdotdev** [driftingruby/186-nested-forms-from-scratch-with-stimulusjs#1]
https://gorails.com/episodes/dynamic-nested-forms-with-stimulus-js

would be nice to give some credit

anyway, I don't know, I'm not operating gorails or anything, just used the nested form code as a base and heavily modified it now

**Comment by kobaltz** [comment]
https://github.com/chentianwei411/saintbayautomation/blob/master/app/javascript/controllers/nested_form_controller.js is where I found the original implementation. I do not subscribe to gorails to see other implementations, but it's great to see other rails content and sites thriving.

**Comment by localhostdotdev** [comment]
oh ok, cool cool cool (I do not subscribe to gorails either, just found it with google a few weeks ago :D)
